services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      # Use environment variables from the host when available. These are
      # substituted by docker compose at runtime. Defaults are provided.
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data

